nodeLinker: isolated

overrides:
  "@typescript-eslint/eslint-plugin": ">=4.4.1"
  "@typescript-eslint/parser": ">=4.4.1"
  "node-notifier": "^8.0.1"

packages:
  - packages/*

## Disable "Update available" banner (updates are handled by Renovate)
updateNotifier: false
