ignoredBuiltDependencies:
  - nx ## Calls verifyOrUpdateNxCloudClient

linkWorkspacePackages: true

nodeLinker: isolated

overrides:
  "@typescript-eslint/eslint-plugin": ">=4.4.1"
  "@typescript-eslint/parser": ">=4.4.1"
  "node-notifier": "^8.0.1"

packages:
  - packages/*

patchedDependencies:
  "@changesets/changelog-github": patches/@changesets__changelog-github.patch

## Disable "Update available" banner (updates are handled by Renovate)
updateNotifier: false
