ignoredBuiltDependencies:
  - nx ## Calls verifyOrUpdateNxCloudClient

linkWorkspacePackages: true

nodeLinker: isolated

packages:
  - packages/*

## Disable "Update available" banner (updates are handled by Renovate)
updateNotifier: false
