name: Release

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  release:
    environment: release
    if: github.repository == 'kachkaev/reusable-stuff'
    name: Release
    permissions:
      contents: write
      id-token: write
      pull-requests: write
    runs-on: ubuntu-24.04
    steps:
      - name: Check out repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Set up pnpm and Node.js, install dependencies
        uses: pnpm/setup@703c52620218391530e48b9e8870d5c0082e1b9b # v2.1.0
        with:
          cache: true

      - name: Create release pull request or publish to npm
        id: changesets
        uses: changesets/action@8488615a623b1b9c987934bb89eae8af6a946ac1 # v2.1.1
        with:
          publish: pnpm changesets:publish
          title: "Version packages"
          version: pnpm changesets:version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
